export const player1Tracks = [
  { id: 1, title: 'arschvoll', fileRaw: '1J_tjXmXvCEsjsgebqeoDeBXIvBnZukC2' },
  { id: 2, title: 'exitus', fileRaw: '1jQnx9AD4G0mA9POMkH5Z40l6Gygp5U0O' },
  { id: 3, title: 'dicke männer in meinem schornsteinschacht', fileRaw: '1u80-QGdcR0fddQ_CycVbXy95eoo0RWkq' },
  { id: 4, title: 'femme fatale hat sich togelacht', fileRaw: '1-_akicgdMGMSPHjXVsB-tgsqRCyyzcFy' },
  { id: 5, title: 'gefühlstechnisch', fileRaw: '1DJYIHM1z44qdXf_Pm9tjX3tcBYi1Km1Q' },
  { id: 6, title: 'butterweich', fileRaw: '1D3ZvwOkjYrOXA5xNVy7D_GcdGSQAyDqZ' },
  { id: 7, title: 'fluss', fileRaw: '1OKIbmZlk5iBP9xccNop53GsyQtvPNfxE' },
  { id: 8, title: 'lalilove', fileRaw: '1v18wQyazriQPEZ0w-tKBnXNEKHcd6eqh' },
  { id: 9, title: 'lowlifespielerpolitikfickzeit vorbei', fileRaw: '1t6NWG7pSnEC31Cyx8HIEnI1jHmWhAKkC' },
  { id: 10, title: 'melodie', fileRaw: '1x3vK_V126mX08gLqBeDcwscHWf9t2iH-' },
  { id: 11, title: 'nice', fileRaw: '1j5G51R3I8sqMk9aDJgltUZx7xYHnCXFo' },
  { id: 12, title: 'party', fileRaw: '131QUabmPIL0D_MaC2nBVRl4G9czLu1sx' },
  { id: 13, title: 'paralyze', fileRaw: '1mCTVWcZCHFbmC0fGH0n2ick-B9Dl3K-p' },
  { id: 14, title: 'pfand II', fileRaw: '1K0DvPFD6aABlisSVB9tgpDebE1QTKnbd' },
  { id: 15, title: 'danke an jesus', fileRaw: '1tLxkZ1T7RxzUMT19SOihMjcf7Ly1rRJK' },
  { id: 16, title: 'schizo nur ein shizo', fileRaw: '131sCnZ9FhwHjtRbpBHpEUUbkljgnpO5V' }
].map(t => ({ id: 'p1-' + t.id, title: t.title, file: 'https://docs.google.com/uc?export=download&id=' + t.fileRaw }));

export const player2Tracks = [
  { id: 'p2-1', title: '11brief', file: 'https://docs.google.com/uc?export=download&id=1wAAIafBNn1HTcPE6nf3jQUfErOBD6JQD' },
  { id: 'p2-2', title: 'amd', file: 'https://docs.google.com/uc?export=download&id=1Ul1ErCTseVcBF5pDwjasDdbs1kzjrKmI' },
  { id: 'p2-3', title: 'bahn macht mobil', file: 'https://docs.google.com/uc?export=download&id=1I4T9uOEUGA6JymPb0s9bqFTEQo85Umwg' },
  { id: 'p2-4', title: 'blutschrift', file: 'https://docs.google.com/uc?export=download&id=11umt_vpg140sJdVnzz9FtNrDmjURuZ6l' },
  { id: 'p2-5', title: 'brothers in arms', file: 'https://docs.google.com/uc?export=download&id=1XgGDeZ65zqfKi6HVU7PGtR0I87XMPHJ6' },
  { id: 'p2-6', title: 'code-koller', file: 'https://docs.google.com/uc?export=download&id=1AJrh10AB8y6fnUD06xgUcmh5IjlsAPXv' },
  { id: 'p2-7', title: 'das war kein witz', file: 'https://docs.google.com/uc?export=download&id=1OZtpfLiKCsUOLZ_2n9WL-ufz4qF3b5Wm' },
  { id: 'p2-8', title: 'dem ownen', file: 'https://docs.google.com/uc?export=download&id=17AkdYHh52y5h-UJkU7tgEl5gkcHan4Yv' },
  { id: 'p2-9', title: 'die komplette endzerfickung', file: 'https://docs.google.com/uc?export=download&id=1bLapFu107x7_sxsA9LndKTFOb7w0H3aI' },
  { id: 'p2-10', title: 'don geilo ein memoir', file: 'https://docs.google.com/uc?export=download&id=1GDK7W6Brwe8XCi9poPd4S1de-0kCNT_y' },
  { id: 'p2-11', title: 'dringendkrankgebingt', file: 'https://docs.google.com/uc?export=download&id=1FVnlAxmp1RkFjqo4KFNlKFxAGcC5yGvt' },
  { id: 'p2-12', title: 'du doofnuss', file: 'https://docs.google.com/uc?export=download&id=1Wwdv71r8986XCZcutAyHOucB7BgB1mor' },
  { id: 'p2-13', title: 'eis', file: 'https://docs.google.com/uc?export=download&id=1EF3NaOWnQLRZhecV-buznc8OKE6C4zja' },
  { id: 'p2-14', title: 'englich', file: 'https://docs.google.com/uc?export=download&id=1DdklRPngtom00ynTrkRfbHTrQdbnuutc' },
  { id: 'p2-15', title: 'exitus', file: 'https://docs.google.com/uc?export=download&id=1ipWlSl9OuOOay9epS1AiGGe2Q-FsvT4U' },
  { id: 'p2-16', title: 'exmatrikuliert', file: 'https://docs.google.com/uc?export=download&id=1jshQNdAfVKOtsEI4YsL0E0h-fXBq-6Ib' },
  { id: 'p2-17', title: 'farben', file: 'https://docs.google.com/uc?export=download&id=1CHYJInHGUztCwQdEwNkkTOHV9OS7UdN3' },
  { id: 'p2-18', title: 'felgenreinigerdiõt', file: 'https://docs.google.com/uc?export=download&id=1HDps24cmVEV6i6JLDab9hdgXwen0P8LH' },
  { id: 'p2-19', title: 'fructose is in ohrdnung', file: 'https://docs.google.com/uc?export=download&id=1l5IEgRJ16BkW-CYU6jXUdrnVvsuahWig' },
  { id: 'p2-20', title: 'gefangen in der zeit', file: 'https://docs.google.com/uc?export=download&id=1hrE0aedyky1eyURKgp-PGnEWTNI0beOK' },
  { id: 'p2-21', title: 'Hail Christ!', file: 'https://docs.google.com/uc?export=download&id=1n8AltNCB8KB2swuBuLQP0RMAiD6riavU' },
  { id: 'p2-22', title: 'himmel2', file: 'https://docs.google.com/uc?export=download&id=1B2INHcaaOt72mZsI6VsUgrGJb5dFwkdD' },
  { id: 'p2-23', title: 'ketakev', file: 'https://docs.google.com/uc?export=download&id=1p5qHW95YWOPh7PsCVj8a_7CbIiKk4q3C' },
  { id: 'p2-24', title: 'kino der toten', file: 'https://docs.google.com/uc?export=download&id=1HO84Sp22ZXvysL_EqBt8yjDyWmiONDjw' },
  { id: 'p2-25', title: 'knzi', file: 'https://docs.google.com/uc?export=download&id=1_IrRFKgtee3zh4UMGMXeTzKZMjSgTXnn' },
  { id: 'p2-26', title: 'lennyderpenner', file: 'https://docs.google.com/uc?export=download&id=1p_kyn354nQWvJY77VY0_dIjq4vC7_US2' },
  { id: 'p2-27', title: 'lifeline', file: 'https://docs.google.com/uc?export=download&id=1RWVI-EcV8qUBUvv_QQmf9siQOLaJ7fJt' },
  { id: 'p2-28', title: 'like a g666', file: 'https://docs.google.com/uc?export=download&id=1Au5bgUb3ivzTSAggFXl0-5Cj9y8O0mrE' },
  { id: 'p2-29', title: 'lillith', file: 'https://docs.google.com/uc?export=download&id=1BJmB0b7scH0LElErqTBUEWw3Wiu_8FyV' },
  { id: 'p2-30', title: 'lunte', file: 'https://docs.google.com/uc?export=download&id=1bS1pkmGultnGOnoHP4ITkD7JorJcgBlc' },
  { id: 'p2-31', title: 'matrixausbrecher', file: 'https://docs.google.com/uc?export=download&id=1EhFWi4spd6wU1KFoZD59c4EXTrq7vrvd' },
  { id: 'p2-32', title: 'melodie', file: 'https://docs.google.com/uc?export=download&id=1du48NOBOkT0tR8ZC3qu2fTEe2L4otdqU' },
  { id: 'p2-33', title: 'nice', file: 'https://docs.google.com/uc?export=download&id=1Mro8SyjCDaGkLs5C6SkrzqjBUTPmsrhi' },
  { id: 'p2-34', title: 'niemals II', file: 'https://docs.google.com/uc?export=download&id=1w9mvNgrOAE4-eMBqB8wIAsKQqi6hQSWJ' },
  { id: 'p2-35', title: 'nin', file: 'https://docs.google.com/uc?export=download&id=1ZzdGV8ItIR4eQUOKXjiLj_tEIUfSiTfx' },
  { id: 'p2-36', title: 'pfand II', file: 'https://docs.google.com/uc?export=download&id=1odC9ntUKWMuMcyN5DyFUvTdudqoTOFWO' },
  { id: 'p2-37', title: 'pfand III', file: 'https://docs.google.com/uc?export=download&id=1B4RfXIj1ounzNenQzDA0Pr0UcZ7GoUFM' },
  { id: 'p2-38', title: 'pfand', file: 'https://docs.google.com/uc?export=download&id=1-GYt9gFq0NIjNwYMyX5MaququSVgpY_o' },
  { id: 'p2-39', title: 'politik', file: 'https://docs.google.com/uc?export=download&id=1cCMq_mfg1GbZmrynSqKh--IJ3IfFBaBd' },
  { id: 'p2-40', title: 'puffreis', file: 'https://docs.google.com/uc?export=download&id=1rXOIqJEi3t3Yg-OWL2PBm-CnJnC-8smn' },
  { id: 'p2-41', title: 'random go xg', file: 'https://docs.google.com/uc?export=download&id=1bOi-lgRpVVh11SQeiX_0imoZ-9I5FKNi' },
  { id: 'p2-42', title: 'rewemeinmarkt', file: 'https://docs.google.com/uc?export=download&id=1L9pHsqkdCWPd_J5ABZH80bBVwr1bJB9W' },
  { id: 'p2-43', title: 'riesige rostige ÷lpumpe mitnem knall', file: 'https://docs.google.com/uc?export=download&id=1Qr7uKSAzD4APQVVklJrRmSsvh252N_85' },
  { id: 'p2-44', title: 'schlecht', file: 'https://docs.google.com/uc?export=download&id=14WPSuWm0l0_XhrEfkTJys5YWC8gW3fiv' },
  { id: 'p2-45', title: 'schleifentrick', file: 'https://docs.google.com/uc?export=download&id=1VpfByrSn86SitvCfJTAboRCvK5y0aJoa' },
  { id: 'p2-46', title: 'schrottreif', file: 'https://docs.google.com/uc?export=download&id=1B0tYEAowAXAZAJgo1lFGWB4rsJkVr-cS' },
  { id: 'p2-47', title: 'stiernacken', file: 'https://docs.google.com/uc?export=download&id=10Jf_UmJOgpqlTz0fkDSiJbmZaJOonAsY' },
  { id: 'p2-48', title: 'stralsund', file: 'https://docs.google.com/uc?export=download&id=1OyERhELMjrucePwIS4XOAbRcDQZ70chZ' },
  { id: 'p2-49', title: 'sulfat', file: 'https://docs.google.com/uc?export=download&id=1800U-1yPDOD16SS_3vyBkfNPg8pPkSs4' },
];

export const allTracks = [...player1Tracks, ...player2Tracks];
