export const player1Tracks = [
  { id: 1, title: 'arschvoll', fileRaw: '1J_tjXmXvCEsjsgebqeoDeBXIvBnZukC2' },
  { id: 2, title: 'exitus', fileRaw: '1jQnx9AD4G0mA9POMkH5Z40l6Gygp5U0O' },
  { id: 3, title: 'dicke männer in meinem schornsteinschacht', fileRaw: '1u80-QGdcR0fddQ_CycVbXy95eoo0RWkq' },
  { id: 4, title: 'femme fatale hat sich togelacht', fileRaw: '1-_akicgdMGMSPHjXVsB-tgsqRCyyzcFy' },
  { id: 5, title: 'gefühlstechnisch', fileRaw: '1DJYIHM1z44qdXf_Pm9tjX3tcBYi1Km1Q' },
  { id: 6, title: 'butterweich', fileRaw: '1D3ZvwOkjYrOXA5xNVy7D_GcdGSQAyDqZ' },
  { id: 7, title: 'fluss', fileRaw: '1OKIbmZlk5iBP9xccNop53GsyQtvPNfxE' },
  { id: 8, title: 'lalilove', fileRaw: '1v18wQyazriQPEZ0w-tKBnXNEKHcd6eqh' },
  { id: 9, title: 'lowlifespielerpolitikfickzeit vorbei', fileRaw: '1t6NWG7pSnEC31Cyx8HIEnI1jHmWhAKkC' },
  { id: 10, title: 'melodie', fileRaw: '1x3vK_V126mX08gLqBeDcwscHWf9t2iH-' },
  { id: 11, title: 'nice', fileRaw: '1j5G51R3I8sqMk9aDJgltUZx7xYHnCXFo' },
  { id: 12, title: 'party', fileRaw: '131QUabmPIL0D_MaC2nBVRl4G9czLu1sx' },
  { id: 13, title: 'paralyze', fileRaw: '1mCTVWcZCHFbmC0fGH0n2ick-B9Dl3K-p' },
  { id: 14, title: 'pfand II', fileRaw: '1K0DvPFD6aABlisSVB9tgpDebE1QTKnbd' },
  { id: 15, title: 'danke an jesus', fileRaw: '1tLxkZ1T7RxzUMT19SOihMjcf7Ly1rRJK' },
  { id: 16, title: 'schizo nur ein shizo', fileRaw: '131sCnZ9FhwHjtRbpBHpEUUbkljgnpO5V' },
  { id: 17, title: 'guitar rig 7', fileRaw: '1PFTh1NiJHKhD79I4Q_gOhUyT6nl1wAvu' }
].map(t => ({ id: 'p1-' + t.id, title: t.title, file: `/music/${t.title}.mp3` }));

export const player2Tracks = [
  { id: 'p2-1', title: '11brief', file: '/api/drive/audio/1wAAIafBNn1HTcPE6nf3jQUfErOBD6JQD' },
  { id: 'p2-2', title: 'amd', file: '/api/drive/audio/1Ul1ErCTseVcBF5pDwjasDdbs1kzjrKmI' },
  { id: 'p2-3', title: 'bahn macht mobil', file: '/api/drive/audio/1I4T9uOEUGA6JymPb0s9bqFTEQo85Umwg' },
  { id: 'p2-4', title: 'blutschrift', file: '/api/drive/audio/11umt_vpg140sJdVnzz9FtNrDmjURuZ6l' },
  { id: 'p2-5', title: 'brothers in arms', file: '/api/drive/audio/1XgGDeZ65zqfKi6HVU7PGtR0I87XMPHJ6' },
  { id: 'p2-6', title: 'code-koller', file: '/api/drive/audio/1AJrh10AB8y6fnUD06xgUcmh5IjlsAPXv' },
  { id: 'p2-7', title: 'das war kein witz', file: '/api/drive/audio/1OZtpfLiKCsUOLZ_2n9WL-ufz4qF3b5Wm' },
  { id: 'p2-8', title: 'dem ownen', file: '/api/drive/audio/17AkdYHh52y5h-UJkU7tgEl5gkcHan4Yv' },
  { id: 'p2-9', title: 'die komplette endzerfickung', file: '/api/drive/audio/1bLapFu107x7_sxsA9LndKTFOb7w0H3aI' },
  { id: 'p2-10', title: 'don geilo ein memoir', file: '/api/drive/audio/1GDK7W6Brwe8XCi9poPd4S1de-0kCNT_y' },
  { id: 'p2-11', title: 'dringendkrankgebingt', file: '/api/drive/audio/1FVnlAxmp1RkFjqo4KFNlKFxAGcC5yGvt' },
  { id: 'p2-12', title: 'du doofnuss', file: '/api/drive/audio/1Wwdv71r8986XCZcutAyHOucB7BgB1mor' },
  { id: 'p2-13', title: 'eis', file: '/api/drive/audio/1EF3NaOWnQLRZhecV-buznc8OKE6C4zja' },
  { id: 'p2-14', title: 'englich', file: '/api/drive/audio/1DdklRPngtom00ynTrkRfbHTrQdbnuutc' },
  { id: 'p2-15', title: 'exitus', file: '/api/drive/audio/1ipWlSl9OuOOay9epS1AiGGe2Q-FsvT4U' },
  { id: 'p2-16', title: 'exmatrikuliert', file: '/api/drive/audio/1jshQNdAfVKOtsEI4YsL0E0h-fXBq-6Ib' },
  { id: 'p2-17', title: 'farben', file: '/api/drive/audio/1CHYJInHGUztCwQdEwNkkTOHV9OS7UdN3' },
  { id: 'p2-18', title: 'felgenreinigerdiõt', file: '/api/drive/audio/1HDps24cmVEV6i6JLDab9hdgXwen0P8LH' },
  { id: 'p2-19', title: 'fructose is in ohrdnung', file: '/api/drive/audio/1l5IEgRJ16BkW-CYU6jXUdrnVvsuahWig' },
  { id: 'p2-20', title: 'gefangen in der zeit', file: '/api/drive/audio/1hrE0aedyky1eyURKgp-PGnEWTNI0beOK' },
  { id: 'p2-21', title: 'Hail Christ!', file: '/api/drive/audio/1n8AltNCB8KB2swuBuLQP0RMAiD6riavU' },
  { id: 'p2-22', title: 'himmel2', file: '/api/drive/audio/1B2INHcaaOt72mZsI6VsUgrGJb5dFwkdD' },
  { id: 'p2-23', title: 'ketakev', file: '/api/drive/audio/1p5qHW95YWOPh7PsCVj8a_7CbIiKk4q3C' },
  { id: 'p2-24', title: 'kino der toten', file: '/api/drive/audio/1HO84Sp22ZXvysL_EqBt8yjDyWmiONDjw' },
  { id: 'p2-25', title: 'knzi', file: '/api/drive/audio/1_IrRFKgtee3zh4UMGMXeTzKZMjSgTXnn' },
  { id: 'p2-26', title: 'lennyderpenner', file: '/api/drive/audio/1p_kyn354nQWvJY77VY0_dIjq4vC7_US2' },
  { id: 'p2-27', title: 'lifeline', file: '/api/drive/audio/1RWVI-EcV8qUBUvv_QQmf9siQOLaJ7fJt' },
  { id: 'p2-28', title: 'like a g666', file: '/api/drive/audio/1Au5bgUb3ivzTSAggFXl0-5Cj9y8O0mrE' },
  { id: 'p2-29', title: 'lillith', file: '/api/drive/audio/1BJmB0b7scH0LElErqTBUEWw3Wiu_8FyV' },
  { id: 'p2-30', title: 'lunte', file: '/api/drive/audio/1bS1pkmGultnGOnoHP4ITkD7JorJcgBlc' },
  { id: 'p2-31', title: 'matrixausbrecher', file: '/api/drive/audio/1EhFWi4spd6wU1KFoZD59c4EXTrq7vrvd' },
  { id: 'p2-32', title: 'melodie', file: '/api/drive/audio/1du48NOBOkT0tR8ZC3qu2fTEe2L4otdqU' },
  { id: 'p2-33', title: 'nice', file: '/api/drive/audio/1Mro8SyjCDaGkLs5C6SkrzqjBUTPmsrhi' },
  { id: 'p2-34', title: 'niemals II', file: '/api/drive/audio/1w9mvNgrOAE4-eMBqB8wIAsKQqi6hQSWJ' },
  { id: 'p2-35', title: 'nin', file: '/api/drive/audio/1ZzdGV8ItIR4eQUOKXjiLj_tEIUfSiTfx' },
  { id: 'p2-36', title: 'pfand II', file: '/api/drive/audio/1odC9ntUKWMuMcyN5DyFUvTdudqoTOFWO' },
  { id: 'p2-37', title: 'pfand III', file: '/api/drive/audio/1B4RfXIj1ounzNenQzDA0Pr0UcZ7GoUFM' },
  { id: 'p2-38', title: 'pfand', file: '/api/drive/audio/1-GYt9gFq0NIjNwYMyX5MaququSVgpY_o' },
  { id: 'p2-39', title: 'politik', file: '/api/drive/audio/1cCMq_mfg1GbZmrynSqKh--IJ3IfFBaBd' },
  { id: 'p2-40', title: 'puffreis', file: '/api/drive/audio/1rXOIqJEi3t3Yg-OWL2PBm-CnJnC-8smn' },
  { id: 'p2-41', title: 'random go xg', file: '/api/drive/audio/1bOi-lgRpVVh11SQeiX_0imoZ-9I5FKNi' },
  { id: 'p2-42', title: 'rewemeinmarkt', file: '/api/drive/audio/1L9pHsqkdCWPd_J5ABZH80bBVwr1bJB9W' },
  { id: 'p2-43', title: 'riesige rostige ÷lpumpe mitnem knall', file: '/api/drive/audio/1Qr7uKSAzD4APQVVklJrRmSsvh252N_85' },
  { id: 'p2-44', title: 'schlecht', file: '/api/drive/audio/14WPSuWm0l0_XhrEfkTJys5YWC8gW3fiv' },
  { id: 'p2-45', title: 'schleifentrick', file: '/api/drive/audio/1VpfByrSn86SitvCfJTAboRCvK5y0aJoa' },
  { id: 'p2-46', title: 'schrottreif', file: '/api/drive/audio/1B0tYEAowAXAZAJgo1lFGWB4rsJkVr-cS' },
  { id: 'p2-47', title: 'stiernacken', file: '/api/drive/audio/10Jf_UmJOgpqlTz0fkDSiJbmZaJOonAsY' },
  { id: 'p2-48', title: 'stralsund', file: '/api/drive/audio/1OyERhELMjrucePwIS4XOAbRcDQZ70chZ' },
  { id: 'p2-49', title: 'sulfat', file: '/api/drive/audio/1800U-1yPDOD16SS_3vyBkfNPg8pPkSs4' },
  { id: 'p2-50', title: 'automatik MG', file: '/api/drive/audio/1MEG-Y9Uz-oJvoRq9abaydCkbqssKLu_y' },
  { id: 'p2-51', title: 'shizophren', file: '/api/drive/audio/1e2u66MkTPJn_cTeRKfxKCqvvzy9vvTdZ' },
];

export const folderTracks = [
  { id: 1, title: 'danke an jesus', file: '/music/RSHBKR/danke an jesus.mp3' },
  { id: 2, title: 'dicke männer in meinem schornsteinschacht', file: '/music/RSHBKR/dicke männer in meinem schornsteinschacht.mp3' },
  { id: 3, title: 'femme fatale hat sich togelacht', file: '/music/RSHBKR/femme fatale hat sich togelacht.mp3' },
  { id: 4, title: 'gefühlstechnisch', file: '/music/RSHBKR/gefühlstechnisch.mp3' },
  { id: 5, title: 'guitar rig 7', file: '/music/RSHBKR/guitar rig 7.mp3' },
  { id: 6, title: 'hypnose', file: '/music/RSHBKR/hypnose.mp3' },
  { id: 7, title: 'lowlifespielerpolitikfickzeit vorbei', file: '/music/RSHBKR/lowlifespielerpolitikfickzeit vorbei.mp3' },
  { id: 8, title: 'melodie', file: '/music/RSHBKR/melodie.mp3' },
  { id: 9, title: 'pfand II', file: '/music/RSHBKR/pfand II.mp3' },
].map(t => ({ id: 'p3-' + t.id, title: t.title, file: t.file }));

export const allTracks = [...player1Tracks, ...player2Tracks, ...folderTracks];
